### ISSUE TITLE
Potential naming conflict with smplx

### ISSUE THREAD

**Issue by msalvato** [otaheri/GRAB#1]
### Issue
Upon installing the required dependencies and smplx, I am met with the following error when running visualize_grab.py (occurs regardless of arguments passed in).
```
$ python examples/visualize_grab.py
Traceback (most recent call last):
  File "examples/visualize_grab.py", line 25, in <module>
    from tools.objectmodel import ObjectModel
  File "/home/msalvato/miniconda3/envs/myenv2/lib/python3.8/site-packages/tools/__init__.py", line 18, in <module>
    import clean_ch
ModuleNotFoundError: No module named 'clean_ch'
```
### Configurations
Linux (WSL 2) in a conda env (python 3.8.3)
Linux (WSL 2) in a pip env (python 3.8.3 I think?)
Windows in a conda env (python 3.8.3)

### Min repro
I checked a min repo in WSL 2 in a new conda env with python 3.8.3
1) 'pip install -r requirements.txt' in GRAB
2) 'pip install smplx[all]' and 'python setup.py install' for smplx. 
3) python examples/visualize_grab.py

### Solution
I renamed the "tools" module in GRAB to "tools_grab" (and changed all references). I believe the issue is that smplx creates a package named "tools" which also exists as a name in GRAB.

**Comment by otaheri** [comment]
Thanks for reporting the issue. As you mentioned the problem was with the smplx package which installed the tools folder as a separate package. Now it is fixed in the smplx and it should work here without any additional change.
