### ISSUE TITLE
Relation between right-hand global_orientation and wrist joint from full-body pose

### ISSUE THREAD

**Issue by purvaten** [otaheri/GRAB#11]
Hi,

I am trying to see if I can get the right hand wrist global_orientation from full body pose. My understanding is that the 21 full body joints correspond to [these](https://github.com/vchoutas/smplx/blob/master/smplx/joint_names.py#L19-L39) specific joints. The last joint is the right wrist.

However, the value for `data['body']['body_pose'][-1, :]` does not appear to be the same as `data['rhand']['global_orient']`. Should these two be the same / related? If so, is there a way for me to get right hand global orientation (wrist pose) from the full-body pose?

Thanks!

**Comment by otaheri** [comment]
Hi @purvaten,

No, the global_orient of the hand is not the same as the last joint of the body. Also, please note that the body should have 55 joints, not 21. If you have 21 joints, you are using the SMPL model most probably, not the SMPLX model.

To get the global rotation of the hand or any other joint, please use [this](https://github.com/otaheri/GOAL/blob/a287d9979c01a425ce83dafd396c88cc95b6bdc2/tools/utils.py#L222) function. As input, it takes the pose_parameter and as output, it will give you the global rotation for each joint.
