### ISSUE TITLE
Correspondence between MANO and SMPL hand_pose

### ISSUE THREAD

**Issue by purvaten** [otaheri/GRAB#12]
Hi,

I noticed that the `right_hand_pose` PCA provided in `body` parameters is different from `rhand_hand_pose` PCA provided in `rhand` parameters in GRAB data. So when I replace the `rhand` pose (either fullpose or PCA) as is into SMPLX the hand looks different. I was wondering -- given a MANO pose parameter (fullpose or PCA), is there a way to convert it into `right_hand_pose` for SMPLX?

Here is an example: **Left** - right_hand_pose from body param ; **Right** - hand_pose from rhand param
<p float="left">
  <img src="https://user-images.githubusercontent.com/13128829/184236748-d6aae8ee-0168-453d-bdc3-3c3c25848f8c.png" width="250" height="250" />
  <img src="https://user-images.githubusercontent.com/13128829/184236846-14277ab3-f399-49a6-b395-d53c230c8cb6.png" width="250" height="250"/> 
</p>

Thanks!

**Comment by Borzyszkowski** [comment]
Hi! I'm not sure if this is relevant, but perhaps the hand should be flattened using [flat_hand_mean](https://github.com/vchoutas/smplx/blob/master/smplx/body_models.py#L1504) option from SMPL-X. I also wrote about it in [this issue](https://github.com/otaheri/GRAB/issues/10).

**Comment by purvaten** [comment]
@Borzyszkowski yup you are right! Looks like that was the issue after all. Thank you so much!
