### ISSUE TITLE
Incorrect Hand-Object Contact 

### ISSUE THREAD

**Issue by zhangy76** [otaheri/GRAB#16]
Hi,

Thank you for sharing the great work! When visualizing the data, I obtain incorrect hand-oject contacts as the examples shown below: 
![1](https://github.com/otaheri/GRAB/assets/60193243/b2ce2a1d-df7e-48c7-a9a0-7c6c6012ab6d)
![2](https://github.com/otaheri/GRAB/assets/60193243/fdf0aab4-6188-4598-80ba-9006ab5c520e)

The hand and object mesh are obtained from the MANO hand data (pose, shape, global rotation, translation) and object data (object template, object global rotation, translation). I wonder if there are errors in my visualization process or the data can include these errors?

Yufei

**Comment by zhangy76** [comment]
There are some problems with my visualization process. Closs the issue.

**Comment by bb0928** [comment]
i encountered similar issue. could you share about how you solved it? thanks

**Comment by CENHM** [comment]
> i encountered similar issue. could you share about how you solved it? thanks

So do I. Have you solve this problem?

**Comment by zhangy76** [comment]
sorry it seems I solved the issue but I forgot what I have done

**Comment by CENHM** [comment]
> sorry it seems I solved the issue but I forgot what I have done

That's sad😢but thanks for your reply

**Comment by bb0928** [comment]
> > sorry it seems I solved the issue but I forgot what I have done
> 
> That's sad😢but thanks for your reply

hi i've solved this issue.
I applied the translation and rotation matrix directly to the vertices of the object(rigid body), rather than applying the matrix to a center of the rigid body. I think it is because the "center" is inaccurate.

**Comment by CENHM** [comment]
> > > sorry it seems I solved the issue but I forgot what I have done
> > 
> > 
> > That's sad😢but thanks for your reply
> 
> hi i've solved this issue. I applied the translation and rotation matrix directly to the vertices of the object(rigid body), rather than applying the matrix to a center of the rigid body. I think it is because the "center" is inaccurate.

That's it! Thanks!

**Comment by Sherlock1956** [comment]
> > > > sorry it seems I solved the issue but I forgot what I have done
> > > 
> > > 
> > > That's sad😢but thanks for your reply
> > 
> > 
> > hi i've solved this issue. I applied the translation and rotation matrix directly to the vertices of the object(rigid body), rather than applying the matrix to a center of the rigid body. I think it is because the "center" is inaccurate.
> 
> That's it! Thanks!

Hello! I recently encountered the same issue and tried to visualize the hand and object using the following script. However, I noticed that the hand doesn't seem to make contact with the object. I’m sorry for not fully understanding your previous comment about applying the translation and rotation matrix directly to the vertices of the rigid body, instead of applying it to the center of the body. Could you please help me figure out where the problem might be? Thank you in advance!
```
import numpy as np
import sys
import os
import trimesh
import torch
import random
from scipy.spatial.transform import Rotation as R
from manotorch.manolayer import ManoLayer, MANOOutput
sys.path.append("/Users/lyx/Downloads/dataset/grab")
from GRAB.tools.utils import parse_npz

hand_data_root = "/Users/lyx/Downloads/dataset/grab/data"
def handle_data(hand_data_folder):
    file_name_list = os.listdir(hand_data_folder)
    # random.shuffle(file_name_list)
    for file_name in file_name_list:
        file_path = os.path.join(hand_data_folder, file_name)
        data = parse_npz(file_path)
        rhand_parameter = data['rhand']
        hand_beta_path = '_'.join(rhand_parameter['vtemp'].split('_')[:-1])+'_rhand_betas.npy'
        hand_beta_path = os.path.join(hand_data_root,hand_beta_path)
        hand_beta = torch.from_numpy(np.load(hand_beta_path)).to(torch.float32)
        global_orient = rhand_parameter['params']['global_orient']
        transl = torch.from_numpy(rhand_parameter['params']['transl'])
        fullpose = rhand_parameter['params']['fullpose']
        obj_path = os.path.join(hand_data_root, data['object']['object_mesh'])
        obj_mesh = trimesh.load(obj_path)
        obj_transl = data['object']['params']['transl']
        obj_global_orient = data['object']['params']['global_orient']
        selected_frame = np.argmax(data['contact']['object'].sum(1))
        obj_transl = obj_transl[selected_frame]
        obj_global_orient = obj_global_orient[selected_frame]
        fullpose = fullpose[selected_frame]
        global_orient = global_orient[selected_frame]
        transl = transl[selected_frame]
        rotation = R.from_rotvec(obj_global_orient)
        rotation_matrix = rotation.as_matrix()
        rot_matrix_4 = np.eye(4)
        rot_matrix_4[:3,:3] = rotation_matrix
        rot_matrix_4[:3,3] = obj_transl
        obj_mesh.apply_transform(rot_matrix_4)
        mano_layer = ManoLayer(mano_assets_root="/Users/lyx/Downloads/dataset/OkaInk/image/manotorch/assets/mano", flat_hand_mean=True, center_idx=0)
        hand_faces = mano_layer.get_mano_closed_faces()
        axis_angle = torch.from_numpy(np.concatenate([global_orient, fullpose]))
        mano_out: MANOOutput = mano_layer(
            axis_angle.unsqueeze(0),
            hand_beta.unsqueeze(0))
        hand_verts = mano_out.verts.squeeze(0).numpy() + transl.numpy()
        hand_mesh = trimesh.Trimesh(vertices=hand_verts, faces=hand_faces)
        concat_mesh = trimesh.util.concatenate(hand_mesh, obj_mesh)
        concat_mesh.show()
if __name__ == "__main__":
    for i in range(1,11):
        hand_data_folder = os.path.join(hand_data_root,'grab', f"s{i}")
        handle_data(hand_data_folder)
```
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/b138cebf-41a9-47a8-990e-e96601f2e003" />
