### ISSUE TITLE
details about global_orient

### ISSUE THREAD

**Issue by binbinbai** [otaheri/GRAB#18]
Thank you for your great work!!!!
I want to ask about the global_orient parameter in rhand. Does it describe the rotation of the root node of the middle finger of the palm in a fixed world coordinate system?

**Comment by otaheri** [comment]
Hi @binbinbai, the global_orient represents the global rotation of the wrist for the hand models (rhand or lhand parameters). For the body parameters, it represents the global rotation of the pelvis.

**Comment by binbinbai** [comment]
Thank you so much!!!
