### ISSUE TITLE
per vertex displacement error

### ISSUE THREAD

**Issue by vru2020** [otaheri/GRAB#4]
Hello @otaheri 

I am trying to extract the vertices of the body. As described, I run the  the get_grab_vertices.py

```
python grab/save_grab_vertices.py --grab-path $GRAB_DATASET_PATH \
                                 --model-path $SMPLX_MODEL_FOLDER 
```

I am getting an error related to the vertex displacement in the function blend_shapes

`RuntimeError: size of dimension does not match previous size, operand 1, dim 2`

How can I get it work？I didn't modify anything in the code just gave the model path and the data path. Thanks

**Comment by otaheri** [comment]
Hi there, this could be due to giving a wrong model-path to the code. I can take a look if you send me a snapshot of the error and also the model-path that you are passing as input.
