### ISSUE TITLE
HTTP ERROR 500 for https://grab.is.tue.mpg.de/de

### ISSUE THREAD

**Issue by buaacyw** [otaheri/GRAB#5]
Thanks for your great work!
But I meet HTTP ERROR 500 when tried to open https://grab.is.tue.mpg.de/de.
I don't get problems on other websites and the solutions for this error found on websites can't help.
Can you help me? Thanks!

**Comment by knsjoon** [comment]
@buaacyw I have the same exact problem currently still

**Comment by otaheri** [comment]
Dear @knsjoon and @buaacyw,
Thank you for your message, we are taking a look into this and will let you know once it is resolved. Hopefully, it will be back in less than one hour.

**Comment by knsjoon** [comment]
> Dear @knsjoon and @buaacyw,
> Thank you for your message, we are taking a look into this and will let you know once it is resolved. Hopefully, it will be back in less than one hour.

It works now! Thank you for a quick fix : )  Amazing work by the way!

**Comment by buaacyw** [comment]
Thanks!

**Comment by buaacyw** [comment]
Sorry but I meet HTTP ERROR 500 again
